### ISSUE TITLE
B1 Feedback

### ISSUE THREAD

**Issue by yuliaUU** [stat545ubc-2021/STAT545-Assignments-tzuyilu#1]
Great work🎈🎈🎈

just two major things to adjust:

1. the function is too rigid: it only takes one specific dataset. adjust the function so that any other dataset can be provided
2.  function is too simple. You can obtain your output in three lines of code, which defeats the purpose of the function. try to add may be a visual to the extracted dataset or additional output of summary stats for the selected group

**Comment by tzuyilu** [comment]
Thank you for your advice. I have modified my functions and made them become more general in Assignment_B-2. I hope it is better!

**Comment by tzuyilu** [comment]
Thank you for your advice. I have modified my functions and made them become more general in Assignment_B-2. I hope it is better!
